version: '3'

services:
  web1:
    image: my-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./src1:/usr/share/nginx/html

  web2:
    image: my-nginx-container
    ports:
      - "8082:80"
    volumes:
      - ./src2:/usr/share/nginx/html

  web3:
    image: my-nginx-container
    ports:
      - "8083:80"
    volumes:
      - ./src3:/usr/share/nginx/html

  web4:
    image: my-nginx-container
    ports:
      - "8084:80"
    volumes:
      - ./src4:/usr/share/nginx/html

  web5:
    image: my-nginx-container
    ports:
      - "8085:80"
    volumes:
      - ./src5:/usr/share/nginx/html